# Generated by Django 2.1.5 on 2019-02-05 09:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetingMinutes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetingMinutes',
            new_name='MeetingMinute',
        ),
    ]
