# Generated by Django 2.1.5 on 2019-02-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingMinutes', '0002_auto_20190205_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminute',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meetingminute',
            name='name',
            field=models.TextField(),
        ),
    ]
