# Generated by Django 2.1.5 on 2019-02-05 09:41

from django.db import migrations, models
import meetingMinutes.models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingMinutes', '0003_auto_20190205_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingminute',
            name='name',
        ),
        migrations.AddField(
            model_name='meetingminute',
            name='title',
            field=models.CharField(default='asdf', help_text='Must be a unique title.', max_length=240, unique=True, verbose_name='Meeting Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingminute',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meetingminute',
            name='voice_recording_file',
            field=models.FileField(upload_to=meetingMinutes.models.user_directory_path, verbose_name='Voice Recording File'),
        ),
    ]
