# Generated by Django 2.1.5 on 2019-02-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingMinutes', '0004_auto_20190205_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingminute',
            options={'verbose_name': 'Meeting Minute', 'verbose_name_plural': 'Meeting Minutes'},
        ),
    ]
