# Generated by Django 2.1.5 on 2019-02-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingMinutes', '0006_meetingminute_meeting_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminute',
            name='meeting_transcript',
            field=models.TextField(blank=True, null=True, verbose_name='Meeting Transcript'),
        ),
    ]
