# Generated by Django 2.1.5 on 2019-03-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingMinutes', '0007_auto_20190215_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminute',
            name='meeting_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Meeting Summary'),
        ),
    ]
