# Generated by Django 2.1.5 on 2019-03-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingMinutes', '0008_meetingminute_meeting_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminute',
            name='speaker_count',
            field=models.IntegerField(default=3, verbose_name='Speaker Count'),
            preserve_default=False,
        ),
    ]
